language: cpp

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
    - nodejs
    - npm

install:
  - rm -rf node_modules
  - npm install
  - npm install gulp

script:
  - make npm_test
