language: cpp

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
    - nodejs
    - npm

install:
  - rm -rf node_modules
  - npm install
  - npm install gulp
  - which nodejs
  - ls /home/travis/build/physycom/physycom_beta/node_modules/gulp/bin/gulp.js

script:
  - npm test
  - alias gulp="/usr/bin/nodejs /home/travis/build/physycom/physycom_beta/node_modules/gulp/bin/gulp.js $@"
  - gulp
